# ==============================================================================
# Generated by qmake (2.01a) (Qt 4.6.0) on: Wed Jan 6 18:50:35 2010
# This file is generated by qmake and should not be modified by the
# user.
#  Name        : Makefile
#  Description : Wrapper Makefile for calling Symbian build tools
#
# ==============================================================================


MAKEFILE          = Makefile
QMAKE             = c:\Qt\4.6.0\bin\qmake
DEL_FILE          = del
DEL_DIR           = rmdir
MOVE              = move
XCOPY             = xcopy /d /f /h /r /y /i
ABLD              = ABLD.BAT
DEBUG_PLATFORMS   = winscw gcce armv5 armv6
RELEASE_PLATFORMS = gcce armv5 armv6
MAKE              = make

ifeq (WINS,$(findstring WINS, $(PLATFORM)))
ZDIR=$(EPOCROOT)epoc32\release\$(PLATFORM)\$(CFG)\Z
else
ZDIR=$(EPOCROOT)epoc32\data\z
endif

DEFINES	 = -DSYMBIAN -DUNICODE -DQT_KEYPAD_NAVIGATION -DQT_SOFTKEYS_ENABLED -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
INCPATH	 =  -I"C:/Qt/4.6.0/include/QtCore" -I"C:/Qt/4.6.0/include/QtCore/tmp" -I"C:/Qt/4.6.0/include/QtNetwork" -I"C:/Qt/4.6.0/include/QtNetwork/tmp" -I"C:/Qt/4.6.0/include/QtGui" -I"C:/Qt/4.6.0/include/QtGui/tmp" -I"C:/Qt/4.6.0/include" -I"C:/Qt/4.6.0/include/tmp" -I"C:/Qt/4.6.0/mkspecs/common/symbian" -I"C:/Qt/4.6.0/mkspecs/common/symbian/tmp" -I"C:/S60/devices/S60_5th_Edition_SDK_v1.0/epoc32/include" -I"C:/Symbian/Carbide/workspace/aciedit" -I"C:/Symbian/Carbide/workspace/aciedit/tmp" -I"C:/S60/devices/S60_5th_Edition_SDK_v1.0/epoc32/include/stdapis" -I"C:/S60/devices/S60_5th_Edition_SDK_v1.0/epoc32/include/stdapis/sys" -I"C:/S60/devices/S60_5th_Edition_SDK_v1.0/epoc32/include/stdapis/stlport" -I"C:/S60/devices/S60_5th_Edition_SDK_v1.0/epoc32/include/domain/middleware" -I"C:/S60/devices/S60_5th_Edition_SDK_v1.0/epoc32/include/domain/middleware/loc"
first: default
default: debug-winscw
all: debug release

qmake:
	$(QMAKE) -spec symbian-abld -o "bld.inf" "C:/Symbian/Carbide/workspace/aciedit/aciedit.pro"

bld.inf:
	$(QMAKE)

$(ABLD): bld.inf
	bldmake bldfiles

debug: $(ABLD)
	$(ABLD) build winscw udeb
	$(ABLD) build gcce udeb
	$(ABLD) build armv5 udeb
	$(ABLD) build armv6 udeb

release: $(ABLD)
	$(ABLD) build gcce urel
	$(ABLD) build armv5 urel
	$(ABLD) build armv6 urel

debug-winscw: $(ABLD)
	$(ABLD) build winscw udeb
debug-gcce: $(ABLD)
	$(ABLD) build gcce udeb
debug-armv5: $(ABLD)
	$(ABLD) build armv5 udeb
debug-armv6: $(ABLD)
	$(ABLD) build armv6 udeb
release-gcce: $(ABLD)
	$(ABLD) build gcce urel
release-armv5: $(ABLD)
	$(ABLD) build armv5 urel
release-armv6: $(ABLD)
	$(ABLD) build armv6 urel

export: $(ABLD)
	$(ABLD) export

cleanexport: $(ABLD)
	$(ABLD) cleanexport

C:\Qt\4.6.0\bin\moc.exe:
	(cd $(QTDIR)/src/tools/moc && $(MAKE))

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_TextEditInputContext.cpp moc_CentralWidget.cpp moc_TextEdit.cpp moc_TextStorage.cpp moc_aciedit.cpp moc_keyboard.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_TextEditInputContext.cpp moc_CentralWidget.cpp moc_TextEdit.cpp moc_TextStorage.cpp moc_aciedit.cpp moc_keyboard.cpp 2> NUL
moc_TextEditInputContext.cpp: TextEditInputContext.h \
		..\..\..\..\Qt\4.6.0\bin\moc.exe
	C:\Qt\4.6.0\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN TextEditInputContext.h -o moc_TextEditInputContext.cpp

moc_CentralWidget.cpp: CentralWidget.h \
		..\..\..\..\Qt\4.6.0\bin\moc.exe
	C:\Qt\4.6.0\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN CentralWidget.h -o moc_CentralWidget.cpp

moc_TextEdit.cpp: libimli.h \
		TextStorage.h \
		PieceChain.h \
		TextEdit.h \
		..\..\..\..\Qt\4.6.0\bin\moc.exe
	C:\Qt\4.6.0\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN TextEdit.h -o moc_TextEdit.cpp

moc_TextStorage.cpp: libimli.h \
		PieceChain.h \
		TextStorage.h \
		..\..\..\..\Qt\4.6.0\bin\moc.exe
	C:\Qt\4.6.0\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN TextStorage.h -o moc_TextStorage.cpp

moc_aciedit.cpp: libimli.h \
		aciedit.h \
		..\..\..\..\Qt\4.6.0\bin\moc.exe
	C:\Qt\4.6.0\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN aciedit.h -o moc_aciedit.cpp

moc_keyboard.cpp: libimli.h \
		ui_keyboard.h \
		keyboard.h \
		..\..\..\..\Qt\4.6.0\bin\moc.exe
	C:\Qt\4.6.0\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN keyboard.h -o moc_keyboard.cpp

compiler_rcc_make_all: qrc_aciedit.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_aciedit.cpp 2> NUL
qrc_aciedit.cpp: aciedit.qrc
	c:\Qt\4.6.0\bin\rcc -name aciedit aciedit.qrc -o qrc_aciedit.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp 2> NUL
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_aciedit.h ui_keyboard.h
compiler_uic_clean:
	-$(DEL_FILE) ui_aciedit.h ui_keyboard.h 2> NUL
ui_aciedit.h: aciedit.ui
	c:\Qt\4.6.0\bin\uic.exe aciedit.ui -o ui_aciedit.h

ui_keyboard.h: keyboard.ui
	c:\Qt\4.6.0\bin\uic.exe keyboard.ui -o ui_keyboard.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

create_temps:
	-@ if NOT EXIST "C:\Qt\4.6.0\include\QtCore\tmp" mkdir "C:\Qt\4.6.0\include\QtCore\tmp"
	-@ if NOT EXIST "C:\Qt\4.6.0\include\QtNetwork\tmp" mkdir "C:\Qt\4.6.0\include\QtNetwork\tmp"
	-@ if NOT EXIST "C:\Qt\4.6.0\include\QtGui\tmp" mkdir "C:\Qt\4.6.0\include\QtGui\tmp"
	-@ if NOT EXIST "C:\Qt\4.6.0\include\tmp" mkdir "C:\Qt\4.6.0\include\tmp"
	-@ if NOT EXIST "C:\Qt\4.6.0\mkspecs\common\symbian\tmp" mkdir "C:\Qt\4.6.0\mkspecs\common\symbian\tmp"
	-@ if NOT EXIST "C:\Symbian\Carbide\workspace\aciedit\tmp" mkdir "C:\Symbian\Carbide\workspace\aciedit\tmp"

extension_clean: compiler_clean
	-@ if EXIST "C:\Qt\4.6.0\include\QtCore\tmp" rmdir  /S /Q  "C:\Qt\4.6.0\include\QtCore\tmp"
	-@ if EXIST "C:\Qt\4.6.0\include\QtNetwork\tmp" rmdir  /S /Q  "C:\Qt\4.6.0\include\QtNetwork\tmp"
	-@ if EXIST "C:\Qt\4.6.0\include\QtGui\tmp" rmdir  /S /Q  "C:\Qt\4.6.0\include\QtGui\tmp"
	-@ if EXIST "C:\Qt\4.6.0\include\tmp" rmdir  /S /Q  "C:\Qt\4.6.0\include\tmp"
	-@ if EXIST "C:\Qt\4.6.0\mkspecs\common\symbian\tmp" rmdir  /S /Q  "C:\Qt\4.6.0\mkspecs\common\symbian\tmp"
	-@ if EXIST "C:\Symbian\Carbide\workspace\aciedit\tmp" rmdir  /S /Q  "C:\Symbian\Carbide\workspace\aciedit\tmp"

pre_targetdeps: \
	generated_sources \
	all_source_deps \
	ui_aciedit.h \
	ui_keyboard.h

generated_sources: \
	moc_TextEditInputContext.cpp \
	moc_CentralWidget.cpp \
	moc_TextEdit.cpp \
	moc_TextStorage.cpp \
	moc_aciedit.cpp \
	moc_keyboard.cpp \
	qrc_aciedit.cpp

all_source_deps: \
	TextEditInputContext.h \
	TextEdit.h \
	libimli.h \
	TextStorage.h \
	PieceChain.h \
	CentralWidget.h \
	aciedit.h \
	keyboard.h \
	ui_keyboard.h \
	Dictionary.h \
	ListBox.h \
	version.h

finalize:

winscw_deployment:
	-echo Deploying changed files...
	-$(XCOPY) "c:\Symbian\Carbide\workspace\aciedit\IFiles\langfiles\asamiya_inscript.key" "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\"
	-$(XCOPY) "c:\Symbian\Carbide\workspace\aciedit\IFiles\langfiles\asamiya_phonetic.key" "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\"
	-$(XCOPY) "c:\Symbian\Carbide\workspace\aciedit\IFiles\langfiles\bangla_inscript.key" "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\"
	-$(XCOPY) "c:\Symbian\Carbide\workspace\aciedit\IFiles\langfiles\bangla_phonetic.key" "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\"
	-$(XCOPY) "c:\Symbian\Carbide\workspace\aciedit\IFiles\langfiles\braille_inscript.key" "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\"
	-$(XCOPY) "c:\Symbian\Carbide\workspace\aciedit\IFiles\langfiles\braille_phonetic.key" "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\"
	-$(XCOPY) "c:\Symbian\Carbide\workspace\aciedit\IFiles\langfiles\gujarati_inscript.key" "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\"
	-$(XCOPY) "c:\Symbian\Carbide\workspace\aciedit\IFiles\langfiles\gujarati_phonetic.key" "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\"
	-$(XCOPY) "c:\Symbian\Carbide\workspace\aciedit\IFiles\langfiles\hindi_inscript.key" "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\"
	-$(XCOPY) "c:\Symbian\Carbide\workspace\aciedit\IFiles\langfiles\hindi_phonetic.key" "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\"
	-$(XCOPY) "c:\Symbian\Carbide\workspace\aciedit\IFiles\langfiles\kannada_inscript.key" "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\"
	-$(XCOPY) "c:\Symbian\Carbide\workspace\aciedit\IFiles\langfiles\kannada_phonetic.key" "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\"
	-$(XCOPY) "c:\Symbian\Carbide\workspace\aciedit\IFiles\langfiles\malayala_inscript.key" "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\"
	-$(XCOPY) "c:\Symbian\Carbide\workspace\aciedit\IFiles\langfiles\marathi_inscript.key" "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\"
	-$(XCOPY) "c:\Symbian\Carbide\workspace\aciedit\IFiles\langfiles\marathi_phonetic.key" "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\"
	-$(XCOPY) "c:\Symbian\Carbide\workspace\aciedit\IFiles\langfiles\oriya_inscript.key" "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\"
	-$(XCOPY) "c:\Symbian\Carbide\workspace\aciedit\IFiles\langfiles\oriya_phonetic.key" "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\"
	-$(XCOPY) "c:\Symbian\Carbide\workspace\aciedit\IFiles\langfiles\punjabi_inscript.key" "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\"
	-$(XCOPY) "c:\Symbian\Carbide\workspace\aciedit\IFiles\langfiles\punjabi_phonetic.key" "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\"
	-$(XCOPY) "c:\Symbian\Carbide\workspace\aciedit\IFiles\langfiles\romantrans_inscript.key" "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\"
	-$(XCOPY) "c:\Symbian\Carbide\workspace\aciedit\IFiles\langfiles\romantrans_phonetic.key" "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\"
	-$(XCOPY) "c:\Symbian\Carbide\workspace\aciedit\IFiles\langfiles\sanskrit_inscript.key" "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\"
	-$(XCOPY) "c:\Symbian\Carbide\workspace\aciedit\IFiles\langfiles\sanskrit_phonetic.key" "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\"
	-$(XCOPY) "c:\Symbian\Carbide\workspace\aciedit\IFiles\langfiles\tamil_inscript.key" "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\"
	-$(XCOPY) "c:\Symbian\Carbide\workspace\aciedit\IFiles\langfiles\tamil_phonetic.key" "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\"
	-$(XCOPY) "c:\Symbian\Carbide\workspace\aciedit\IFiles\langfiles\telugu_inscript.key" "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\"
	-$(XCOPY) "c:\Symbian\Carbide\workspace\aciedit\IFiles\langfiles\telugu_phonetic.key" "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\"
	-$(XCOPY) "c:\Symbian\Carbide\workspace\aciedit\IFiles\langfiles\generic.cnj" "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\"
	-$(XCOPY) "c:\Symbian\Carbide\workspace\aciedit\IFiles\langfiles\generic.con" "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\"
	-$(XCOPY) "c:\Symbian\Carbide\workspace\aciedit\IFiles\langfiles\generic.spl" "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\"
	-$(XCOPY) "c:\Symbian\Carbide\workspace\aciedit\IFiles\langfiles\generic.vow" "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\"
	-$(XCOPY) "c:\Symbian\Carbide\workspace\aciedit\IFiles\tabfiles\bangla.tab" "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\tabfiles\"
	-$(XCOPY) "c:\Symbian\Carbide\workspace\aciedit\IFiles\tabfiles\gujarati.tab" "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\tabfiles\"
	-$(XCOPY) "c:\Symbian\Carbide\workspace\aciedit\IFiles\tabfiles\hindi.tab" "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\tabfiles\"
	-$(XCOPY) "c:\Symbian\Carbide\workspace\aciedit\IFiles\tabfiles\kannada.tab" "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\tabfiles\"
	-$(XCOPY) "c:\Symbian\Carbide\workspace\aciedit\IFiles\tabfiles\marathi.tab" "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\tabfiles\"
	-$(XCOPY) "c:\Symbian\Carbide\workspace\aciedit\IFiles\tabfiles\oriya.tab" "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\tabfiles\"
	-$(XCOPY) "c:\Symbian\Carbide\workspace\aciedit\IFiles\tabfiles\romantrans.tab" "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\tabfiles\"
	-$(XCOPY) "c:\Symbian\Carbide\workspace\aciedit\IFiles\tabfiles\tamil.tab" "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\tabfiles\"
	-$(XCOPY) "c:\Symbian\Carbide\workspace\aciedit\IFiles\tabfiles\telugu.tab" "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\tabfiles\"
	-$(XCOPY) "c:\Symbian\Carbide\workspace\aciedit\IFiles\fontmap.ini" "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\"

winscw_deployment_clean:
	-@ if EXIST "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\asamiya_inscript.key" $(DEL_FILE)  "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\asamiya_inscript.key"
	-@ if EXIST "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\asamiya_phonetic.key" $(DEL_FILE)  "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\asamiya_phonetic.key"
	-@ if EXIST "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\bangla_inscript.key" $(DEL_FILE)  "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\bangla_inscript.key"
	-@ if EXIST "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\bangla_phonetic.key" $(DEL_FILE)  "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\bangla_phonetic.key"
	-@ if EXIST "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\braille_inscript.key" $(DEL_FILE)  "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\braille_inscript.key"
	-@ if EXIST "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\braille_phonetic.key" $(DEL_FILE)  "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\braille_phonetic.key"
	-@ if EXIST "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\gujarati_inscript.key" $(DEL_FILE)  "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\gujarati_inscript.key"
	-@ if EXIST "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\gujarati_phonetic.key" $(DEL_FILE)  "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\gujarati_phonetic.key"
	-@ if EXIST "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\hindi_inscript.key" $(DEL_FILE)  "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\hindi_inscript.key"
	-@ if EXIST "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\hindi_phonetic.key" $(DEL_FILE)  "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\hindi_phonetic.key"
	-@ if EXIST "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\kannada_inscript.key" $(DEL_FILE)  "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\kannada_inscript.key"
	-@ if EXIST "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\kannada_phonetic.key" $(DEL_FILE)  "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\kannada_phonetic.key"
	-@ if EXIST "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\malayala_inscript.key" $(DEL_FILE)  "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\malayala_inscript.key"
	-@ if EXIST "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\marathi_inscript.key" $(DEL_FILE)  "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\marathi_inscript.key"
	-@ if EXIST "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\marathi_phonetic.key" $(DEL_FILE)  "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\marathi_phonetic.key"
	-@ if EXIST "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\oriya_inscript.key" $(DEL_FILE)  "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\oriya_inscript.key"
	-@ if EXIST "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\oriya_phonetic.key" $(DEL_FILE)  "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\oriya_phonetic.key"
	-@ if EXIST "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\punjabi_inscript.key" $(DEL_FILE)  "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\punjabi_inscript.key"
	-@ if EXIST "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\punjabi_phonetic.key" $(DEL_FILE)  "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\punjabi_phonetic.key"
	-@ if EXIST "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\romantrans_inscript.key" $(DEL_FILE)  "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\romantrans_inscript.key"
	-@ if EXIST "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\romantrans_phonetic.key" $(DEL_FILE)  "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\romantrans_phonetic.key"
	-@ if EXIST "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\sanskrit_inscript.key" $(DEL_FILE)  "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\sanskrit_inscript.key"
	-@ if EXIST "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\sanskrit_phonetic.key" $(DEL_FILE)  "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\sanskrit_phonetic.key"
	-@ if EXIST "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\tamil_inscript.key" $(DEL_FILE)  "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\tamil_inscript.key"
	-@ if EXIST "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\tamil_phonetic.key" $(DEL_FILE)  "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\tamil_phonetic.key"
	-@ if EXIST "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\telugu_inscript.key" $(DEL_FILE)  "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\telugu_inscript.key"
	-@ if EXIST "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\telugu_phonetic.key" $(DEL_FILE)  "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\telugu_phonetic.key"
	-@ if EXIST "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\generic.cnj" $(DEL_FILE)  "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\generic.cnj"
	-@ if EXIST "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\generic.con" $(DEL_FILE)  "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\generic.con"
	-@ if EXIST "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\generic.spl" $(DEL_FILE)  "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\generic.spl"
	-@ if EXIST "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\generic.vow" $(DEL_FILE)  "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\langfiles\generic.vow"
	-@ if EXIST "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\tabfiles\bangla.tab" $(DEL_FILE)  "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\tabfiles\bangla.tab"
	-@ if EXIST "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\tabfiles\gujarati.tab" $(DEL_FILE)  "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\tabfiles\gujarati.tab"
	-@ if EXIST "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\tabfiles\hindi.tab" $(DEL_FILE)  "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\tabfiles\hindi.tab"
	-@ if EXIST "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\tabfiles\kannada.tab" $(DEL_FILE)  "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\tabfiles\kannada.tab"
	-@ if EXIST "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\tabfiles\marathi.tab" $(DEL_FILE)  "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\tabfiles\marathi.tab"
	-@ if EXIST "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\tabfiles\oriya.tab" $(DEL_FILE)  "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\tabfiles\oriya.tab"
	-@ if EXIST "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\tabfiles\romantrans.tab" $(DEL_FILE)  "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\tabfiles\romantrans.tab"
	-@ if EXIST "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\tabfiles\tamil.tab" $(DEL_FILE)  "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\tabfiles\tamil.tab"
	-@ if EXIST "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\tabfiles\telugu.tab" $(DEL_FILE)  "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\tabfiles\telugu.tab"
	-@ if EXIST "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\fontmap.ini" $(DEL_FILE)  "\S60\devices\S60_5th_Edition_SDK_v1.0\epoc32\winscw\c\private\e6a4c06a\fontmap.ini"

sis: restore_build
	$(if $(wildcard aciedit_template.pkg),$(if $(wildcard .make.cache),$(MAKE) -s -f $(MAKEFILE) ok_sis,$(MAKE) -s -f $(MAKEFILE) fail_sis_nocache),$(MAKE) -s -f $(MAKEFILE) fail_sis_nopkg)

ok_sis:
	createpackage.bat $(QT_SIS_OPTIONS) aciedit_template.pkg $(QT_SIS_TARGET) $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

fail_sis_nopkg:
	$(error PKG file does not exist, 'SIS' target is only supported for executables or projects with DEPLOYMENT statement)

fail_sis_nocache:
	$(error Project has to be build before calling 'SIS' target)

restore_build:
-include .make.cache

store_build:
	@echo # ============================================================================== > .make.cache
	@echo # This file is generated by make and should not be modified by the user >> .make.cache
	@echo #  Name        : .make.cache >> .make.cache
	@echo #  Part of     : aciedit >> .make.cache
	@echo #  Description : This file is used to cache last build target for >> .make.cache
	@echo #                make sis target. >> .make.cache
	@echo #  Version     :  >> .make.cache
	@echo # >> .make.cache
	@echo # ============================================================================== >> .make.cache
	@echo. >> .make.cache
	@echo QT_SIS_TARGET ?= $(QT_SIS_TARGET) >> .make.cache

dodistclean:
	-@ if EXIST "c:\Symbian\Carbide\workspace\aciedit\aciedit_template.pkg" $(DEL_FILE)  "c:\Symbian\Carbide\workspace\aciedit\aciedit_template.pkg"
	-@ if EXIST "c:\Symbian\Carbide\workspace\aciedit\Makefile" $(DEL_FILE)  "c:\Symbian\Carbide\workspace\aciedit\Makefile"
	-@ if EXIST "c:\Symbian\Carbide\workspace\aciedit\Makefile_0xE6A4C06A.mk" $(DEL_FILE)  "c:\Symbian\Carbide\workspace\aciedit\Makefile_0xE6A4C06A.mk"
	-@ if EXIST "c:\Symbian\Carbide\workspace\aciedit\aciedit_0xE6A4C06A.mmp" $(DEL_FILE)  "c:\Symbian\Carbide\workspace\aciedit\aciedit_0xE6A4C06A.mmp"
	-@ if EXIST "c:\Symbian\Carbide\workspace\aciedit\aciedit_reg.rss" $(DEL_FILE)  "c:\Symbian\Carbide\workspace\aciedit\aciedit_reg.rss"
	-@ if EXIST "c:\Symbian\Carbide\workspace\aciedit\aciedit.rss" $(DEL_FILE)  "c:\Symbian\Carbide\workspace\aciedit\aciedit.rss"
	-@ if EXIST "c:\Symbian\Carbide\workspace\aciedit\aciedit.loc" $(DEL_FILE)  "c:\Symbian\Carbide\workspace\aciedit\aciedit.loc"
	-@ if EXIST "c:\Symbian\Carbide\workspace\aciedit\.make.cache" $(DEL_FILE)  "c:\Symbian\Carbide\workspace\aciedit\.make.cache"
	-@ if EXIST "c:\Symbian\Carbide\workspace\aciedit\bld.inf" $(DEL_FILE)  "c:\Symbian\Carbide\workspace\aciedit\bld.inf"

distclean: clean dodistclean

clean: $(ABLD)
	-$(ABLD) reallyclean
	-bldmake clean

run:
	-call /S60/devices/S60_5th_Edition_SDK_v1.0/epoc32\release\winscw\udeb\aciedit.exe

